"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import MarketTabs from "../../components/MarketTabs";
import { getPairHistory } from "../../../lib/api";

function linePath(values:{value:number}[],w:number,h:number){if(!values.length)return "";const min=Math.min(...values.map(v=>v.value)),max=Math.max(...values.map(v=>v.value)),range=max-min||1;return values.map((v,i)=>`${i?'L':'M'} ${(i/(values.length-1||1)*w).toFixed(1)} ${(h-(v.value-min)/range*h).toFixed(1)}`).join(" ")}
export default function PairPage({params}:{params:{symbol:string}}){
 const symbol=decodeURIComponent(params.symbol).toUpperCase();const[days,setDays]=useState(30);const[data,setData]=useState<any>(null);const[error,setError]=useState("");
 useEffect(()=>{let live=true;setError("");getPairHistory(symbol,days,"1d").then(x=>{if(live)setData(x)}).catch(e=>{if(live)setError(e instanceof Error?e.message:"Unable to load pair history")});return()=>{live=false}},[symbol,days]);
 const chart=useMemo(()=>{if(!data?.normalized)return null;const all=[...data.normalized.relative,...data.normalized.base,...data.normalized.quote];if(!all.length)return null;const w=760,h=280;return{w,h,relative:linePath(data.normalized.relative,w,h),base:linePath(data.normalized.base,w,h),quote:linePath(data.normalized.quote,w,h)}},[data]);
 return <main className="shell"><MarketTabs/><header className="section"><Link href="/pairs">← Pairs</Link><p className="muted">Pair Research</p><div className="row"><div><h1>{symbol}</h1><p className="muted">Relative performance versus the base and quote assets.</p></div><span className="pill">Binance</span></div></header>
 <section className="card section"><div className="row"><div><h2>Relative Strength</h2><p className="muted">All series are rebased to 100 at the start of the selected period.</p></div><div className="row">{[7,30,90].map(d=><button className={`button ${days===d?"":"secondary"}`} key={d} onClick={()=>setDays(d)}>{d}D</button>)}</div></div>
 {error?<div className="error">{error}</div>:!chart?<p className="muted">Loading Binance history…</p>:<div style={{overflowX:"auto"}}><svg viewBox={`0 0 ${chart.w} ${chart.h}`} width="100%" role="img" aria-label={`${symbol} relative performance chart`}><path d={chart.base} fill="none" stroke="var(--viz-series-2)" strokeWidth="2"/><path d={chart.quote} fill="none" stroke="var(--viz-series-3)" strokeWidth="2"/><path d={chart.relative} fill="none" stroke="var(--viz-accent)" strokeWidth="3"/><line x1="0" x2={chart.w} y1={chart.h/2} y2={chart.h/2} stroke="var(--viz-border)"/><text x="8" y="18" fill="var(--viz-muted)" fontSize="12">Normalized performance</text></svg><div className="row" style={{marginTop:8}}><span><strong style={{color:"var(--viz-accent)"}}>{symbol}</strong></span><span><strong style={{color:"var(--viz-series-2)"}}>{symbol.split("/")[0]}/USDT</strong></span><span><strong style={{color:"var(--viz-series-3)"}}>{symbol.split("/")[1]}/USDT</strong></span></div></div>}</section>
 <section className="grid section"><div className="card"><span className="muted">Pair</span><h2>{data?.pair??symbol}</h2><p className="muted">Current series from Binance history</p></div><div className="card"><span className="muted">Relative move</span><h2>{data?.normalized?.relative?.length?`${(data.normalized.relative.at(-1).value-100).toFixed(1)}%`:"—"}</h2><p className="muted">vs start of selected period</p></div><div className="card"><span className="muted">Period</span><h2>{days}D</h2><p className="muted">Daily candles</p></div></section>
 <section className="section card"><h2>Interpretation</h2><p>{data?.interpretation?.relative_strength??`${symbol} rising means the base asset is outperforming the quote asset.`}</p></section>
 </main>;
}
