import { neon } from "@neondatabase/serverless";
import { calculateResearchStatus } from "./research-status";

interface Env { DATABASE_URL: string; ADMIN_TOKEN?: string; }
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, DELETE, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
function json(data:unknown,status=200):Response{return Response.json(data,{status,headers:{"Cache-Control":"no-store",...corsHeaders}})}
async function body(request:Request){try{return await request.json() as Record<string,unknown>}catch{return null}}
function text(value:unknown){return typeof value==="string"?value.trim():""}
function getAssetId(pathname:string){const m=pathname.match(/^\/api\/assets\/([^/]+)\/?$/);return m?decodeURIComponent(m[1]).toLowerCase():null}
function getPairId(pathname:string){const m=pathname.match(/^\/api\/pairs\/([^/]+)\/?$/);return m?decodeURIComponent(m[1]):null}
function getPairHistorySymbol(pathname:string){const m=pathname.match(/^\/api\/pairs\/([^/]+)\/history\/?$/);return m?decodeURIComponent(m[1]).toUpperCase():null}
function getCommodityId(pathname:string){const m=pathname.match(/^\/api\/commodities\/([^/]+)\/?$/);return m?decodeURIComponent(m[1]):null}
function isAdmin(request:Request,env:Env){return !!env.ADMIN_TOKEN&&request.headers.get("Authorization")===`Bearer ${env.ADMIN_TOKEN}`}
function requireAdmin(request:Request,env:Env){if(!env.ADMIN_TOKEN)return json({status:"error",error:"admin_auth_not_configured"},503);if(!isAdmin(request,env))return json({status:"error",error:"admin_auth_required"},401);return null}

async function binanceKlines(symbol:string,interval:string,limit:number){
 const endpoint=`https://api.binance.com/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}&limit=${limit}`;
 const response=await fetch(endpoint,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error(`Binance ${symbol}: ${response.status}`);const rows=await response.json() as unknown[];
 return rows.map((r:any)=>({time:new Date(Number(r[0])).toISOString(),open:Number(r[1]),high:Number(r[2]),low:Number(r[3]),close:Number(r[4]),volume:Number(r[5])}));
}

export default {async fetch(request:Request,env:Env):Promise<Response>{
 const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders});if(!env.DATABASE_URL)return json({status:"error",service:"crypto-api",database:"not_configured"},500);const sql=neon(env.DATABASE_URL);
 if(url.pathname==="/api/health")return json({status:"ok",service:"crypto-api"});
 if(url.pathname==="/api/db-health"){try{const r=await sql`select now() as now`;return json({status:"ok",service:"crypto-api",database:"ok",now:r[0]?.now??null})}catch{return json({status:"error",service:"crypto-api",database:"unavailable"},503)}}
 if(url.pathname==="/api/admin/db-schema"&&request.method==="GET"){
  const auth=requireAdmin(request,env);if(auth)return auth;
  try{const [tables,columns,constraints,indexes]=await Promise.all([
   sql`select table_schema,table_name from information_schema.tables where table_schema not in ('pg_catalog','information_schema') and table_type='BASE TABLE' order by table_schema,table_name`,
   sql`select table_schema,table_name,column_name,ordinal_position,data_type,udt_name,is_nullable,column_default from information_schema.columns where table_schema not in ('pg_catalog','information_schema') order by table_schema,table_name,ordinal_position`,
   sql`select tc.table_schema,tc.table_name,tc.constraint_name,tc.constraint_type,kcu.column_name,ccu.table_schema as foreign_table_schema,ccu.table_name as foreign_table_name,ccu.column_name as foreign_column_name from information_schema.table_constraints tc left join information_schema.key_column_usage kcu on tc.constraint_name=kcu.constraint_name and tc.table_schema=kcu.table_schema and tc.table_name=kcu.table_name left join information_schema.constraint_column_usage ccu on tc.constraint_name=ccu.constraint_name and tc.table_schema=ccu.table_schema where tc.table_schema not in ('pg_catalog','information_schema') order by tc.table_schema,tc.table_name,tc.constraint_name,kcu.ordinal_position`,
   sql`select schemaname as table_schema,tablename as table_name,indexname as index_name,indexdef as definition from pg_indexes where schemaname not in ('pg_catalog','information_schema') order by schemaname,tablename,indexname`
  ]);return json({status:"ok",service:"crypto-api",schema_source:"postgres_information_schema",read_only:true,generated_at:new Date().toISOString(),tables,columns,constraints,indexes})}catch(error){return json({status:"error",service:"crypto-api",error:"schema_introspection_failed",detail:String(error)},503)}}
 const pairHistory=getPairHistorySymbol(url.pathname);if(pairHistory&&request.method==="GET"){
  const days=Math.min(Math.max(Number(url.searchParams.get("days")??30),1),90),interval=url.searchParams.get("interval")??"1d";if(!["1d","4h","1h"].includes(interval))return json({status:"error",error:"unsupported_interval"},400);
  const limit=Math.min(days*(interval==="1d"?1:interval==="4h"?6:24)+1,1000);const [pair,base,quote]=await Promise.all([binanceKlines(pairHistory.replace("/",""),interval,limit),binanceKlines(pairHistory.split("/")[0]+"USDT",interval,limit),binanceKlines(pairHistory.split("/")[1]+"USDT",interval,limit)]).catch(()=>[null,null,null] as any);if(!pair||!base||!quote)return json({status:"error",error:"binance_history_unavailable",pair:pairHistory},503);
  const baseMap=new Map(base.map((x:any)=>[x.time,x.close])),quoteMap=new Map(quote.map((x:any)=>[x.time,x.close]));const rows=pair.map((p:any)=>{const b=baseMap.get(p.time),q=quoteMap.get(p.time);return {time:p.time,pair:p.close,baseUsd:b??null,quoteUsd:q??null}}).filter((r:any)=>r.baseUsd!==null&&r.quoteUsd!==null);const normalize=(key:"pair"|"baseUsd"|"quoteUsd")=>{const first=rows[0]?.[key];return rows.map((r:any)=>({time:r.time,value:first?Number(((r[key]/first)*100).toFixed(3)):null})).filter((r:any)=>r.value!==null)};
  return json({status:"ok",source:"Binance",pair:pairHistory,interval,days,rows,normalized:{relative:normalize("pair"),base:normalize("baseUsd"),quote:normalize("quoteUsd")},interpretation:{relative_strength:`${pairHistory} rising means the base asset is outperforming the quote asset; falling means the quote asset is outperforming the base asset.`}});
 }
 if(url.pathname==="/api/assets"||url.pathname==="/api/assets/"){
  if(request.method==="POST"){const auth=requireAdmin(request,env);if(auth)return auth;const d=await body(request),symbol=text(d?.symbol).toUpperCase(),name=text(d?.name),category=text(d?.category)||"core",tier=text(d?.research_tier)||"C";if(!symbol||!name)return json({status:"error",error:"symbol_and_name_required"},400);if(!["A","B","C"].includes(tier))return json({status:"error",error:"invalid_research_tier"},400);if(!["core","defi","l1_infrastructure","bitcoin_ecosystem","stablecoin_payments"].includes(category))return json({status:"error",error:"invalid_category"},400);try{const r=await sql`insert into assets(asset_id,symbol,name,category,research_tier,enabled,research_reason) values(${symbol.toLowerCase()},${symbol},${name},${category},${tier},true,'Added through Dynamic Asset Engine') on conflict(asset_id) do update set symbol=excluded.symbol,name=excluded.name,category=excluded.category,research_tier=excluded.research_tier,enabled=true returning asset_id,symbol,name,category,research_tier,enabled`;return json({status:"ok",item:r[0]},201)}catch(error){return json({status:"error",error:"asset_persistence_failed",detail:String(error)},503)}}
  if(request.method!=="GET")return json({status:"error",error:"method_not_allowed"},405);try{const assets=await sql`select a.asset_id,a.symbol,a.name,a.category,a.research_tier,a.enabled,a.binance_symbol,a.fallback_symbols,a.research_reason,a.primary_asset_type_id,at.code as asset_type_code,at.name as asset_type_name,rs.status as research_freshness,rs.reason as research_status_reason,rs.last_research_at,case when coalesce(b.completed,0)=0 then 'not_started' when coalesce(b.monitoring,false) then 'monitoring' when coalesce(b.completed,0)>=15 then 'complete' else 'in_progress' end as research_lifecycle from assets a left join asset_types at on at.asset_type_id=a.primary_asset_type_id left join research_status rs on rs.asset_id=a.asset_id left join lateral (select count(*) filter(where rb.status='complete') as completed,bool_or(rb.block_number=15 and rb.status='complete') as monitoring from research_blocks rb where rb.snapshot_id=rs.snapshot_id) b on true where a.enabled=true order by case a.research_tier when 'A' then 1 when 'B' then 2 when 'C' then 3 else 4 end,a.symbol`;return json({api_version:"1.5.0",assets:assets.map((a:any)=>({...a,research:{lifecycle:a.research_lifecycle,freshness:a.research_freshness}})),count:assets.length,max_assets:50})}catch(error){return json({status:"error",service:"crypto-api",error:"database_query_failed",detail:String(error)},503)}}
  const assetId=getAssetId(url.pathname);if(assetId){
  if(request.method==="DELETE"){const auth=requireAdmin(request,env);if(auth)return auth;try{const r=await sql`update assets set enabled=false,updated_at=now() where asset_id=${assetId} returning asset_id,symbol,enabled`;return r[0]?json({status:"ok",item:r[0]}):json({status:"error",error:"asset_not_found"},404)}catch{return json({status:"error",error:"asset_persistence_failed"},503)}}
  if(request.method!=="GET")return json({status:"error",error:"method_not_allowed"},405);try{const assets=await sql`select a.asset_id,a.symbol,a.name,a.category,a.research_tier,a.enabled,a.binance_symbol,a.fallback_symbols,a.research_reason,a.primary_asset_type_id,a.secondary_asset_type_id,at.code as asset_type_code,at.name as asset_type_name,at.description as asset_type_description,rs.status as research_freshness,rs.reason as research_status_reason,rs.last_research_at,rs.last_major_update_at,rs.next_review_at from assets a left join asset_types at on at.asset_type_id=a.primary_asset_type_id left join research_status rs on rs.asset_id=a.asset_id where a.asset_id=${assetId} limit 1`;if(!assets[0])return json({status:"error",error:"asset_not_found",asset_id:assetId},404);const [metrics,history,researchSnapshots,researchScenarios,scenarioStates,events,sources,blocks,domains,factors,scores,signals]=await Promise.all([
   sql`select distinct on(o.metric_id)o.metric_id,coalesce(o.value_numeric,o.value_integer::numeric) as value,o.value_boolean,o.value_text,o.value_json,o.unit,o.observed_at,o.source_id,o.source_url,o.status,case when o.freshness='CURRENT' then 'fresh' when o.freshness='STALE' then 'stale' when o.freshness='EXPIRED' then 'unknown' else 'unknown' end as freshness,o.revision from observations o where o.asset_id=${assetId} order by o.metric_id,o.observed_at desc,o.revision desc`,
   sql`select candle_open_at,candle_close_at,open_price,high_price,low_price,close_price,volume,quote_volume,trade_count,source_id,source_symbol from market_daily_candles where asset_id=${assetId} order by candle_open_at desc limit 30`,
   sql`select snapshot_id,version,status,title,content,published_at,created_at from research_snapshots where asset_id=${assetId} order by version desc limit 1`,
   sql`select research_scenario_id,scenario_type,probability,assumptions,supporting_evidence,invalidation_conditions,thesis_impact,confidence,created_at from research_scenarios where snapshot_id=(select snapshot_id from research_snapshots where asset_id=${assetId} order by version desc limit 1) order by case scenario_type when 'base' then 1 when 'bull' then 2 when 'bear' then 3 else 4 end`,
   sql`select scenario_state_id,scenario_id,state,confidence,rationale,indicators,observed_at,snapshot_id from scenario_states where asset_id=${assetId} order by observed_at desc limit 20`,
   sql`select event_id,metric_id,event_type,severity,observed_at,details,status,created_at,closed_at from monitoring_events where asset_id=${assetId} order by observed_at desc limit 50`,
   sql`select distinct s.source_id,s.name,s.source_type,s.base_url,s.trust_level,s.description from sources s join observations o on o.source_id=s.source_id where o.asset_id=${assetId} order by s.source_id`,
   sql`select rb.research_block_id,rb.block_number,rb.title,rb.status,rb.summary,rb.analysis,rb.confidence,coalesce(json_agg(json_build_object('code',rd.code,'name',rd.name,'relevance_weight',rbd.relevance_weight,'display_order',rbd.display_order) order by rbd.display_order nulls last,rd.display_order) filter(where rd.research_domain_id is not null),'[]'::json) as domains from research_blocks rb left join research_block_domains rbd on rbd.research_block_id=rb.research_block_id left join research_domains rd on rd.research_domain_id=rbd.research_domain_id where rb.snapshot_id=(select snapshot_id from research_snapshots where asset_id=${assetId} order by version desc limit 1) group by rb.research_block_id order by rb.block_number`,
   sql`select research_domain_id,code,name,description,display_order from research_domains order by display_order`,
   sql`select critical_factor_id,name,description,importance_weight,current_state,trend,confidence,thesis_impact,monitoring_priority,snapshot_id from critical_factors where asset_id=${assetId} order by monitoring_priority nulls last,name`,
   sql`select score_id,score_type,value,scale_min,scale_max,methodology_version,confidence,explanation,calculated_at,snapshot_id from research_scores where asset_id=${assetId} order by calculated_at desc,score_type`,
   sql`select monitoring_signal_id,critical_factor_id,metric_id,monitoring_event_id,name,current_value,previous_value,direction,threshold,threshold_type,thesis_impact,status,confidence,last_updated_at from monitoring_signals where asset_id=${assetId} order by status,name`
  ]);const researchStatus=calculateResearchStatus(blocks.map((b:any)=>({block_number:b.block_number,status:b.status})));const normalizedMetrics=metrics.map((m:any)=>({metric_id:m.metric_id,value:m.value!==null&&m.value!==undefined?Number(m.value):m.value_text??m.value_boolean??m.value_json??null,unit:m.unit,observed_at:m.observed_at,source_id:m.source_id,source_url:m.source_url,status:m.status,freshness:m.freshness,revision:m.revision}));const snapshot=researchSnapshots[0]?{snapshot_id:researchSnapshots[0].snapshot_id,research_version:String(researchSnapshots[0].version),methodology_version:"CryptoResearch v2",research_date:researchSnapshots[0].published_at??researchSnapshots[0].created_at,title:researchSnapshots[0].title,content:researchSnapshots[0].content,status:researchSnapshots[0].status}:null;const freshness=assets[0].research_freshness;return json({api_version:"1.5.0",engine:"DynamicAssetEngine",asset:{...assets[0],research_status:researchStatus.status,research_status_source:"server_engine",research_freshness:freshness,research:{lifecycle:researchStatus.status,freshness}},research_progress:researchStatus,metrics:normalizedMetrics,history:history.reverse(),research_snapshot:snapshot,research_blocks:blocks,research_domains:domains,critical_factors:factors,scores,research_scenarios:researchScenarios,scenario_states:scenarioStates,monitoring_signals:signals,monitoring_events:events,sources})}catch(error){return json({status:"error",service:"crypto-api",error:"database_query_failed",detail:String(error)},503)}}
 if(url.pathname==="/api/pairs"||url.pathname==="/api/pairs/"){if(request.method==="POST"){const auth=requireAdmin(request,env);if(auth)return auth;const d=await body(request),symbol=text(d?.symbol).toUpperCase(),exchange=text(d?.exchange)||null,p=symbol.split("/");if(p.length!==2||!p[0]||!p[1]||p[0]===p[1])return json({status:"error",error:"valid_base_quote_pair_required"},400);try{const assets=await sql`select asset_id,symbol from assets where upper(symbol) in (${p[0]},${p[1]}) limit 2`;if(assets.length<2)return json({status:"error",error:"pair_assets_not_found"},400);const baseAsset=assets.find((a:any)=>String(a.symbol).toUpperCase()===p[0]),quoteAsset=assets.find((a:any)=>String(a.symbol).toUpperCase()===p[1]);if(!baseAsset||!quoteAsset)return json({status:"error",error:"pair_assets_not_found"},400);const r=await sql`insert into market_pairs(symbol,base_asset_id,quote_asset_id,exchange,enabled) values(${symbol},${baseAsset.asset_id},${quoteAsset.asset_id},${exchange},true) on conflict(symbol) do update set base_asset_id=excluded.base_asset_id,quote_asset_id=excluded.quote_asset_id,exchange=excluded.exchange,enabled=true,disabled_at=null returning *`;return json({status:"ok",item:r[0]},201)}catch(error){return json({status:"error",error:"pair_persistence_failed",detail:String(error)},503)}}if(request.method==="GET"){try{const r=await sql`select mp.id,mp.symbol,mp.base_asset_id,ba.symbol as base_asset,mp.quote_asset_id,qa.symbol as quote_asset,mp.exchange,mp.enabled,mp.created_at,mp.disabled_at from market_pairs mp join assets ba on ba.asset_id=mp.base_asset_id join assets qa on qa.asset_id=mp.quote_asset_id where mp.enabled=true order by mp.symbol`;return json({items:r,count:r.length})}catch{return json({status:"error",error:"pair_query_failed"},503)}}return json({status:"error",error:"method_not_allowed"},405)}
 const pairId=getPairId(url.pathname);if(pairId&&request.method==="DELETE"){const auth=requireAdmin(request,env);if(auth)return auth;try{const r=await sql`update market_pairs set enabled=false,disabled_at=now() where id=${pairId}::uuid returning *`;return r[0]?json({status:"ok",item:r[0]}):json({status:"error",error:"pair_not_found"},404)}catch{return json({status:"error",error:"pair_persistence_failed"},503)}}
 if(url.pathname==="/api/commodities"||url.pathname==="/api/commodities/"){if(request.method==="POST"){const auth=requireAdmin(request,env);if(auth)return auth;const d=await body(request),symbol=text(d?.symbol).toUpperCase(),name=text(d?.name),unit=text(d?.unit)||null;if(!symbol||!name)return json({status:"error",error:"symbol_and_name_required"},400);try{const r=await sql`insert into commodities(symbol,name,unit,enabled) values(${symbol},${name},${unit},true) on conflict(symbol) do update set name=excluded.name,unit=excluded.unit,enabled=true returning *`;return json({status:"ok",item:r[0]},201)}catch(error){return json({status:"error",error:"commodity_persistence_failed",detail:String(error)},503)}}if(request.method==="GET"){try{const r=await sql`select * from commodities where enabled=true order by symbol`;return json({items:r,count:r.length})}catch{return json({status:"error",error:"commodity_query_failed"},503)}}return json({status:"error",error:"method_not_allowed"},405)}
 const commodityId=getCommodityId(url.pathname);if(commodityId&&request.method==="DELETE"){const auth=requireAdmin(request,env);if(auth)return auth;try{const r=await sql`update commodities set enabled=false,disabled_at=now() where id=${commodityId}::uuid returning *`;return r[0]?json({status:"ok",item:r[0]}):json({status:"error",error:"commodity_not_found"},404)}catch{return json({status:"error",error:"commodity_persistence_failed"},503)}}
 return json({status:"ok",service:"crypto-api",message:"Crypto API is running"});
}};
